# External Secrets Operator Configuration
installCRDs: true

replicaCount: 2

image:
  repository: ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent

# Service account
serviceAccount:
  create: true
  automount: true
  annotations: {}

# Resources
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  capabilities:
    drop:
      - ALL

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534

# Webhook configuration
webhook:
  create: true
  port: 9443
  replicaCount: 2
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Cert controller
certController:
  create: true
  replicaCount: 2
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Monitoring
serviceMonitor:
  enabled: true
  namespace: external-secrets-system

# Node selector and tolerations
nodeSelector: {}
tolerations: []
affinity: {}

