apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.10.4  # Updated to latest stable version
    helm:
      releaseName: external-secrets
      values: |
        # External Secrets Operator Configuration - AWS Secrets Manager optimized
        installCRDs: true
        crds:
          createClusterExternalSecret: false
          createClusterSecretStore: true
          createPushSecret: false

        # Global settings
        global:
          # Compatibility mode for better stability
          compatibilityMode: ""
          
        # Controller configuration
        replicaCount: 2
        
        image:
          repository: ghcr.io/external-secrets/external-secrets
          tag: ""  # Uses chart appVersion
          pullPolicy: IfNotPresent

        # Service account with improved annotations structure
        serviceAccount:
          create: true
          automount: true
          #annotations: {}
          # Add IRSA annotation if using AWS IAM roles for service accounts
          annotations:
             eks.amazonaws.com/role-arn: arn:aws:iam::339713140038:role/ExternalSecretsRole

        # Enhanced resource configuration
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 200m  # Increased for better performance
            memory: 256Mi  # Increased for better performance

        # Enhanced security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault

        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
          seccompProfile:
            type: RuntimeDefault

        # Webhook configuration with enhanced settings
        webhook:
          create: true
          port: 9443
          replicaCount: 2
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL

        # Cert controller with enhanced configuration
        certController:
          create: true
          replicaCount: 2
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL

        # Enhanced monitoring configuration
        serviceMonitor:
          enabled: true
          namespace: external-secrets-system
          interval: 30s
          scrapeTimeout: 25s

        # Metrics configuration
        metrics:
          listen:
            port: 8080

        # Pod disruption budget for high availability
        podDisruptionBudget:
          enabled: true
          minAvailable: 1

        # Deployment strategy
        deploymentStrategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0

        # Node selector and scheduling
        nodeSelector: {}
        tolerations: []
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - external-secrets
                topologyKey: kubernetes.io/hostname

        # Environment variables for AWS optimization
        env:
          AWS_REGION: us-east-1  # Set your AWS region
          AWS_ROLE_ARN: arn:aws:iam::339713140038:role/ExternalSecretsRole

        # Logging configuration
        log:
          level: info
          format: json

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true  # Performance optimization
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
