apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.11
    helm:
      releaseName: external-secrets
      values: |
        # External Secrets Operator Configuration
        installCRDs: true

        replicaCount: 2

        image:
          repository: ghcr.io/external-secrets/external-secrets
          pullPolicy: IfNotPresent

        # Service account
        serviceAccount:
          create: true
          automount: true
          annotations: {}

        # Resources
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi

        # Security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
              - ALL

        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534

        # Webhook configuration
        webhook:
          create: true
          port: 9443
          replicaCount: 2
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi

        # Cert controller
        certController:
          create: true
          replicaCount: 2
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi

        # Monitoring
        serviceMonitor:
          enabled: true
          namespace: external-secrets-system

        # Node selector and tolerations
        nodeSelector: {}
        tolerations: []
        affinity: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

