# Kube Prometheus Stack Configuration
commonLabels: {}

# Prometheus Operator
prometheusOperator:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Prometheus
prometheus:
  enabled: true
  prometheusSpec:
    replicas: 2
    retention: 30d
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ""  # Use default storage class
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

# Alertmanager
alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 2
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi

# Grafana
grafana:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  # Admin credentials (use secret in production)
  adminPassword: admin123  # Change this!
  
  # Persistent storage
  persistence:
    enabled: true
    size: 10Gi

# Node Exporter
nodeExporter:
  enabled: true

# Kube State Metrics
kubeStateMetrics:
  enabled: true

# CoreDNS monitoring
coreDns:
  enabled: true

# Kubelet monitoring
kubelet:
  enabled: true

# API Server monitoring
kubeApiServer:
  enabled: true

# Controller Manager monitoring
kubeControllerManager:
  enabled: true

# ETCD monitoring
kubeEtcd:
  enabled: true

# Scheduler monitoring
kubeScheduler:
  enabled: true

